project:
  type: website
  output-dir: docs

website:
  site-url: 'https://kolkataruser.github.io/'
  favicon: 'images/logo2.jpg'
  title: "Kolkata R UseR"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - about.qmd
      - href: blog.qmd
        icon: substack
      - href: member.qmd
        icon: people
    right:
      - icon: github
        href: 'https://github.com/kolkataruser/kolkataruser.github.io'

format:
  html:
    backgroundcolor: "#FFFEF1"
    theme: 
      - yeti
      - style.scss
    # css: styles.css
    # toc: true

editor: visual

